directories:
  output: dist-electron
  buildResources: build
appId: com.codetutor.app
productName: Code Tutor
files:
  - filter:
      - dist/**/*
      - ../web/dist/**/*
      - ../api/dist/**/*
      - ../../content/**/*
      - package.json
extraResources:
  - from: ../../content
    to: content
    filter:
      - '**/*'
mac:
  category: public.app-category.education
  target:
    - dmg
    - zip
win:
  target:
    - nsis
    - portable
linux:
  target:
    - AppImage
    - deb
  category: Education
  maintainer: support@codetutor.dev
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Code Tutor
electronVersion: 28.0.0
